#!/usr/bin/env node
// Writes web/assets.generated.mjs (git-ignored) so the browser page uses exactly the repository's current playbook,
// schemas and template. Run it again after changing any of them.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadAssets } from "./assets.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(here, "web", "assets.generated.mjs");
fs.writeFileSync(out, `// GENERATED by prototype/byo-key/build.mjs. Do not edit.\nexport const assets = ${JSON.stringify(loadAssets())};\n`);
console.log(`wrote ${path.relative(process.cwd(), out)}`);
